version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=playersdb
      - MYSQL_ROOT_PASSWORD=saman
      - LANG=C.UTF-8
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/playerdata.sql:/docker-entrypoint-initdb.d/playerdata.sql
volumes:
  mysql-data: